version: '3'

services:
  front-end:
    build: ./front-end
    container_name: docker-frontend
    command: ng serve --host 0.0.0.0 --disable-host-check true
    ports:
      - "4200:4200"
    restart: unless-stopped
#    volumes:
#      - './front-end:/usr/src/app'
  api:
    build: ./App
    container_name: docker-app
    command: npm run start
    restart: unless-stopped
    ports:
      - "1337:1337"
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
  nginx:
    image: nginx:stable-alpine
    container_name: docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - front-end
volumes:
  mongodb_api: